<a href="https://colab.research.google.com/github/Manish2928/DataScience/blob/main/Feature-Engineering/Label_And_Ordinal_And_Target_Guided_Encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Label And Ordinal Encoding**


*   Convert categorical data into numbers, but the important difference is whether the categories have a natural order.

In [2]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [3]:
## Create a simple dataframe
df = pd.DataFrame({
    'color':['red','blue','green','green','red','blue']
})

In [4]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [5]:
lbl_encoder = LabelEncoder()

In [6]:
lbl_encoder.fit_transform(df[['color']])

/usr/local/lib/python3.13/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 0, 1, 1, 2, 0])

In [7]:
lbl_encoder.transform([['red']])

/usr/local/lib/python3.13/dist-packages/sklearn/preprocessing/_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([2])

In [8]:
lbl_encoder.transform([['blue']])

/usr/local/lib/python3.13/dist-packages/sklearn/preprocessing/_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([0])

# **Ordinal Encoding**



*   Ordinal Encoding is used when categories have a real, meaningful order.

In [9]:
## Ordinal Encoder
from sklearn.preprocessing import OrdinalEncoder

In [10]:
# create a sample dataframe with an ordinal  variable
df = pd.DataFrame({
    'size':['small','medium','large','medium','small','large']
})

In [11]:
df

     size
0   small
1  medium
2   large
3  medium
4   small
5   large

In [12]:
## Create an instance of OrdinalEncoder then fit_transform
encoder = OrdinalEncoder(categories=[['small','medium','large']])

In [13]:
encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

In [14]:
new_df = pd.concat([df,pd.DataFrame(encoder.fit_transform(df[['size']]),columns=['size_encoded'])],axis=1)

In [15]:
new_df

     size  size_encoded
0   small           0.0
1  medium           1.0
2   large           2.0
3  medium           1.0
4   small           0.0
5   large           2.0

# **Target Guided Ordinal Encoding**


*   Target Guided Ordinal Encoding is a technique where we encode categories based on their relationship with the target variable.


*   It is a technique used to encode categorical variables based on their relationship with the target variable. This encoding technique is useful
when we have a categorical variable with a large number of unique categories, and we want to use this variable as a feature in our machine
learning model.

* In Target Guided Ordinal Encoding, we replace each category in the categorical variable with a numerical value based on the mean or median
of the target variable for that category. This creates a monotonic relationship between the categorical variable and the target variable, which
can improve the predictive power of our model.

In [16]:
# create a sample dataframe with a categorical variable and target variable

df = pd.DataFrame({
    'city':['New York','London','Paris','Tokyo','New York','Paris'],
    'price':[200,150,300,250,150,320]
})

In [17]:
df

       city  price
0  New York    200
1    London    150
2     Paris    300
3     Tokyo    250
4  New York    150
5     Paris    320

In [19]:
mean_price = df.groupby('city')['price'].mean().to_dict()

In [20]:
mean_price

{'London': 150.0, 'New York': 175.0, 'Paris': 310.0, 'Tokyo': 250.0}

In [21]:
df['city_encoded'] = df['city'].map(mean_price)

In [22]:
df

       city  price  city_encoded
0  New York    200         175.0
1    London    150         150.0
2     Paris    300         310.0
3     Tokyo    250         250.0
4  New York    150         175.0
5     Paris    320         310.0

In [23]:
df[['price','city_encoded']]

   price  city_encoded
0    200         175.0
1    150         150.0
2    300         310.0
3    250         250.0
4    150         175.0
5    320         310.0

In [24]:
import seaborn as sns
df = sns.load_dataset('tips')

In [25]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [26]:
mean_bill = df.groupby('time')['total_bill'].mean().to_dict()

/tmp/ipykernel_2592/3722957593.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  mean_bill = df.groupby('time')['total_bill'].mean().to_dict()

In [27]:
mean_bill

{'Lunch': 17.168676470588235, 'Dinner': 20.79715909090909}

In [28]:
df['time_encoded'] = df['time'].map(mean_bill)

In [33]:
df.head()

   total_bill   tip     sex smoker  day    time  size time_encoded
0       16.99  1.01  Female     No  Sun  Dinner     2    20.797159
1       10.34  1.66    Male     No  Sun  Dinner     3    20.797159
2       21.01  3.50    Male     No  Sun  Dinner     3    20.797159
3       23.68  3.31    Male     No  Sun  Dinner     2    20.797159
4       24.59  3.61  Female     No  Sun  Dinner     4    20.797159

In [31]:
df[['time','time_encoded']]

       time time_encoded
0    Dinner    20.797159
1    Dinner    20.797159
2    Dinner    20.797159
3    Dinner    20.797159
4    Dinner    20.797159
..      ...          ...
239  Dinner    20.797159
240  Dinner    20.797159
241  Dinner    20.797159
242  Dinner    20.797159
243  Dinner    20.797159

[244 rows x 2 columns]